name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main
      - next
    paths:
      - 'docs/**'
      - '.github/workflows/build_publish_docs.yml'

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: pip
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          
      - name: Build docs
        run: |
          cd docs
          make html
        env:
          DOCS_BASE_URL: ${{ vars.DOCS_BASE_URL }}
          DOCS_URL: ${{ vars.DOCS_URL }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
